import type { Metadata } from 'next'
import { AppLayout } from '@components/AppLayout'
import { GeistSans } from 'geist/font/sans';
import '@styles/globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="es" className={GeistSans.className}>
      <body>
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  )
}
